CC = cc

SRC = error_utils.c \
		list_utils.c \
		mini_quick_sort.c \
		misc_utils.c \
		main.c \
		push_actions.c \
		push_swap.c \
		put_index.c \
		radix_sort.c \
		reverse_rotate_actions.c \
		rotate_actions.c \
		string_utils.c \
		swap_actions.c \
		three_number_sort.c \
		add_to_list.c

all :
	$(CC) $(CFLAGS) -g $(SRC) -o push_swap